baseurl: "/"
title: "Daniel Hayes - A Personal Blog"
theme: ghostwriter
languageCode: en-us
copyright: My Name
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Daniel Hayes
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - _index.md
  intro: true
  headline: Daniel Hayes
  description: My Personal Blog
  github: "https://github.com/djhayes1994"
  linkedin: "https://www.linkedin.com/in/djhayes1994/"
  email: djhayes1994@example.com
  opengraph: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""



menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Scripts
      url: /scripts/
      weight: 2
    - name: How-Tos
      url: /how-to/
      weight: 3
    - name: About
      url: /page/about/
      weight: 4
